version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.479.1-lts-jdk17  # 推荐：同版本但用 JDK17
    # 或者
    # image: jenkins/jenkins:lts-jdk17  # 最新 LTS + JDK17（推荐）
    # image: jenkins/jenkins:lts-jdk21  # 最新 LTS + JDK21（最新）
    container_name: jenkins
    restart: on-failure
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
volumes:
  jenkins_data: