version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: on-failure
    privileged: true
    user: root
    group_add:
      - 0
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      # 使用你现有的卷名
      - docker-final-assignment_jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
volumes:
  # 在这里声明你想要使用的外部卷
  docker-final-assignment_jenkins_data:
    external: true
