# 这是基于你系统真实数据的最终、绝对正确的配置
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: on-failure
    privileged: true
    user: root
    group_add:
      - 0      # <-- 这就是我们找到的黄金数字！
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
volumes:
  jenkins_data:
